services:
  webclient:
      build:
        context: ../../..
        dockerfile: ./config/docker/prod/Dockerfile
      ports:
        - 80:80
      volumes:
        - ../../..:/app
        - /app/node_modules